FROM ubuntu:focal as builder

ENV BUILD_DIR=/build
ENV PATH="${PATH}:${BUILD_DIR}/conda/bin:${BUILD_DIR}/bin"
ENV WAGL_VERSION=wagl-5.5.2
ENV EUGL_VERSION=eugl-0.3.1
ENV TESP_VERSION=tesp-0.8.0
ENV LUIGI_VERSION=1.2.1
ENV PYTHONPATH=${BUILD_DIR}/lib/python3.8/site-packages/

USER root

# Build deps
RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git bzip2 ca-certificates gfortran-10 gcc-10 make software-properties-common \
        libpq-dev \
        libgdal-dev \
        python3-skimage

RUN ln -s $(which gfortran-10) $(which gfortran-10 | sed 's/\(.*\)\/\gfortran-10/\1\/gfortran/') \
    && ln -s $(which gcc-10) $(which gcc-10 | sed 's/\(.*\)\/\gcc-10/\1\/gcc/')

WORKDIR ${BUILD_DIR}

ADD https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh /root/miniconda.sh
RUN chmod +x /root/miniconda.sh && /root/miniconda.sh -b -f -p conda

# # Download the necessary codebases (@versions) (using git now as installs needed version info)
RUN git clone --branch master https://github.com/sixy6e/idl-functions.git idl-functions \
    && git clone --branch ${LUIGI_VERSION} https://github.com/spotify/luigi.git luigi \
    && git clone --branch eodatasets3-0.19.3 https://github.com/GeoscienceAustralia/eo-datasets.git eo-datasets \
    && git clone --branch bug/eodatasets-branch-fix https://github.com/jellis/tesp.git tesp \
    && git clone --branch ${EUGL_VERSION} https://github.com/OpenDataCubePipelines/eugl.git eugl \
    && git clone --branch ${WAGL_VERSION} https://github.com/GeoscienceAustralia/wagl.git wagl

# # Force versions
RUN pip install numpy \
    && conda install \
        hdf5==1.12.0 \
        # blosc==1.21.0 \
        click==7.1.2 -y
#     && conda install -c conda-forge gdal==3.3.0

# RUN cd ${BUILD_DIR}/eo-datasets && python setup.py install --prefix=${BUILD_DIR} && rm -rf .git \
#     && cd ${BUILD_DIR}/luigi && python setup.py install --prefix=${BUILD_DIR} && rm -rf .git \
#     && cd ${BUILD_DIR}/idl-functions && python setup.py install --prefix=${BUILD_DIR} && rm -rf .git \
    # && cd ${BUILD_DIR}/wagl && python setup.py install --prefix=${BUILD_DIR} && rm -rf .git
#     && cd ${BUILD_DIR}/tesp && python setup.py install --prefix=${BUILD_DIR} && rm -rf .git
    # && cd ${BUILD_DIR}/eugl && python setup.py install --prefix=${BUILD_DIR} && rm -rf .git